version: "3"

volumes:
  .:
  postgres_data: {}
  data_traefik: {}

services: 
  django:
    build:
      context: .
      dockerfile: ./config/django/Dockerfile
    image: seguridad_django
    volumes:
      - .:/app:z
    depends_on:
      - postgres
    command: /usr/local/bin/gunicorn --workers=4 seguridad.wsgi --bind 0.0.0.0:5000 --chdir=/app --timeout 60
    # command: python seguridad/manage.py runserver

  postgres:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=seguridad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remon123
      
  traefik:
    build:
      context: .
      dockerfile: ./config/traefik/Dockerfile
    image: seguridad_traefik
    depends_on:
      - django
    volumes:
      - data_traefik:/etc/traefik/acme:z
    ports:
      - "80:80"
      - "443:443"
