version: "3"

volumes:
  .:
  postgres_data: {}
  data_traefik: {}

services: 
  django_app:
    build: .
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.rule=Host(`api.rrqq.me`)

  postgres:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=seguridad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remon123
    

  traefik:
    build:
      context: .
      dockerfile: ./config/traefik/Dockerfile
    depends_on:
      - django_app
    volumes:
      - data_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
