version: "3"

volumes:
  .:
  postgres_data: {}
  data_traefik: {}

services: 
  django_app:
    build: .
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=seguridad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remon123
  
  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django_app
    labels: 
      - "traefik.http.routers.nginx.rule=Host(`api.rrqq.me`)"
    
  traefik:
    build:
      context: .
      dockerfile: ./config/traefik/Dockerfile
    depends_on:
      - django_app
    volumes:
      - data_traefik:/etc/traefik/acme:z
    ports:
      - "80:80"
      - "443:443"
