version: "3"

services: 
  django_app:
    build: .
    volumes:
      # - static:/app/static
      - ./app:/app
    expose:
      - 8000
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`api.rrqq.me`)"

  postgres:
    image: postgres:12.3
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  traefik:
    image: traefik:v2.0-alpine
    command: --providers.docker
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  .:
  postgres_data: