version: "3"

services: 
  django_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`api.rrqq.me`)"

  postgres:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=seguridad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remon123

  traefik:
    build:
      context: .
      dockerfile: ./config/traefik/Dockerfile
    command: --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/etc/traefik/acme:z

volumes:
  .:
  postgres_data: {}
  traefik_data: {}