version: "3"

services: 
  django_app:
    build: .
    volumes:
      # - static:/app/static
      - .:/app
    expose:
      - 8000
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`api.rrqq.me`)"

  postgres:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/datata
    environment:
      - POSTGRES_DB=seguridad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remon123
    

  traefik:
    image: traefik:v2.0-alpine
    command: --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  .:
  postgres_data: