version: "3"

services: 
  django_app:
    build: .
    volumes:
      - static:/app/static
      - .:/app
    
  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/app/static
    depends_on:
      - django_app

volumes:
  .:
  static: